# Site settings
title: Newsroom
shortname: 
abbrev: 
email: mustaphazeezat@gmail.com
description: newsroom 
url: "https://newsroom.com"
timezone: Africa/Lagos
language: en


# Handling Reading
charset: 'utf-8'


# Build settings
markdown: kramdown


# Collections
collections:
  uploads:
    title: uploads (Media & Files)
  archives:
    title: archives
    output: true
    permalink: /:collection/:name/
  topics:

  

# Defaults
defaults:
  -scope:
    type: archives
  values:
    layout: single-archive

# Include folders
include:
  - _pages

# Handling Sass
sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore